### PR TITLE
Serialization fix

### PR DESCRIPTION
**Pull request by garlicnation**
The most recent sha was being stored with a version-specific key instead of a request-specific key.

Consequently, when users requested a version of "*"(the default), polygit failed to query for the sha entry and failed to invalidate/repopulate the sha.

This begs for a test that attempts to request the * version of a few repos with a blank backing store.

### CODE REVIEW

**Comment by garlicnation** [comment]
Diffbased on #9. You can hold off reviewing until that's been merged.

**Comment by garlicnation** [comment]
You can use https://github.com/PolymerLabs/polygit2/compare/runPolymerTests...serializationFix to review.

**Comment by garlicnation** [comment]
@justinfagnani PTAL

**Comment by justinfagnani** [comment]
Ok, what does this do?

**Comment by garlicnation** [comment]
@justinfagnani updated description.

**Comment by justinfagnani** [comment]
LGTM, but tests please, eventually :)

**Pull request merged**
